version: "3.9"

services:
    php:
      build: env/phpdocker/php-cli
      entrypoint: ["tail", "-f", "/dev/null"]
      container_name: php
      working_dir: /var/www
      volumes:
        - .:/var/www